title:              PORTFOLIO
email:              chirag05b@gmail.com
description:        The Portfolio by Chirag B
author:             Chirag B
baseurl:            ""
url:                "https://Chirag05B.github.io"

# Social Profiles
twitter_username:
github_username:
facebook_username:
instagram_username: chirag05_b
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
